"use server";

import { GoogleGenAI } from "@google/genai";

// Initialize the Gemini client securely. 
// Uses GEMINI_API_KEY for standard deployments, falling back to NEXT_PUBLIC_GEMINI_API_KEY.
const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
const ai = new GoogleGenAI({ apiKey });

/**
 * Server Action to diagnose plant health using Gemini Multimodal API.
 * 
 * @param imageBase64 - The base64 string of the uploaded plant image.
 * @param mimeType - The MIME type of the image (e.g., 'image/jpeg', 'image/png').
 * @param prompt - The text prompt specifying what to look for.
 * @returns A JSON string or the assistant's diagnosis text.
 */
export async function diagnosePlantHealth(
  imageBase64: string,
  mimeType: string,
  prompt: string
): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-lite-preview", // Using the advanced reasoning model for accurate diagnostics
      contents: {
        parts: [
          {
            inlineData: {
              data: imageBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt || "Analyze this leaf. Identify any diseases (e.g., powdery mildew, nutrient deficiency) and suggest an organic, urban-farming compliant treatment plan. Assess if this node is contributing effectively to carbon sequestration.",
          },
        ],
      },
    });

    const text = response.text;
    
    if (!text) {
      throw new Error("No text response generated by Gemini API.");
    }
    
    return text;
  } catch (error) {
    console.error("Error diagnosing plant health:", error);
    throw new Error("Failed to process plant diagnostic sequence. Sensor interference detected.");
  }
}
